# highlighter: pygments
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://adityagupta679.github.io/resume
author: Aditya Gupta

# edit this section with your information
# biomadeira.github.io - all contents run on /resume/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Aditya Gupta's Resume
name: Aditya Gupta
email: adityagupta679@gmail.com
email_full: mailto:adityagupta679@gmail.com
website: adityagupta679.github.io
website_full: https://adityagupta679.github.io
github: adityagupta679
# twitter: twitter
linkedin: adityagupta679
tel: +91 9419209630 
tel_full: tel:+919419209630
# google_maps: 'https://www.google.co.uk/maps/place/Channi+Himmat,+Jammu,+Jammu+and+Kashmir'
address: 524/3 Channi Himmat
postcode: 180015
city: Jammu
state: Jammu and Kashmir
country: India
google_analytics: 

# needed for travis-ci build
exclude: [vendor]
